# Generated by Django 3.2.3 on 2021-05-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20210516_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Customer',
        ),
    ]
